In [1]:
import pandas as pd 
import numpy as np
import os
import gc
pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings("ignore")

In [1]:
!pip install pandas
!pip install numpy
!pip install openpyxl
!pip install matplotlib
!pip install seaborn
!pip install scikit-learn
!pip install geodatasets

Requirement already satisfied: pandas in c:\users\benutzer_01\miniconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\benutzer_01\miniconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\benutzer_01\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\benutzer_01\miniconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\benutzer_01\miniconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in c:\users\benutzer_01\miniconda3\lib\site-packages (2.3.4)
Requirement already satisfied: openpyxl in c:\users\benutzer_01\miniconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\benutzer_01\miniconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: matplotlib in c:\users\benutzer_01\miniconda3\lib\site-packages (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib) (2.3.4)
Requirement already satisfied: packaging>=20.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\benutzer_01\miniconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in c:\users\benutzer_01\miniconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\benutzer_01\miniconda3\lib\site-packages (from seaborn) (2.3.4)
Requirement already satisfied: pandas>=1.2 in c:\users\benutzer_01\miniconda3\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\benutzer_01\miniconda3\lib\site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\benutzer_01\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\benutzer_01\miniconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\benutzer_01\miniconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\benutzer_01\miniconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: scikit-learn in c:\users\benutzer_01\miniconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from scikit-learn) (2.3.4)
Requirement already satisfied: scipy>=1.8.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: geodatasets in c:\users\benutzer_01\miniconda3\lib\site-packages (2024.8.0)
Requirement already satisfied: pooch in c:\users\benutzer_01\miniconda3\lib\site-packages (from geodatasets) (1.8.2)
Requirement already satisfied: platformdirs>=2.5.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from pooch->geodatasets) (4.3.7)
Requirement already satisfied: packaging>=20.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from pooch->geodatasets) (25.0)
Requirement already satisfied: requests>=2.19.0 in c:\users\benutzer_01\miniconda3\lib\site-packages (from pooch->geodatasets) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\benutzer_01\miniconda3\lib\site-packages (from requests>=2.19.0->pooch->geodatasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\benutzer_01\miniconda3\lib\site-packages (from requests>=2.19.0->pooch->geodatasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\benutzer_01\miniconda3\lib\site-packages (from requests>=2.19.0->pooch->geodatasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\benutzer_01\miniconda3\lib\site-packages (from requests>=2.19.0->pooch->geodatasets) (2025.10.5)

## Calculer la distance entre la france et d'autre pays

### Importation des librairies

In [3]:
df_pays = pd.read_csv("Countries & Territories Taxonomy MVP - C&T Taxonomy with HXL Tags.csv")

In [4]:
print(df_pays.columns.tolist())

['ID', 'RW ID', 'm49 numerical code', 'HPC Tools API ID', 'Appears in UNTERM list', 'Appears in DGACM list', 'Independent', 'Deprecated', 'Has HRP', 'In GHO', 'ISO 3166-1 Alpha 2-Codes', 'ISO 3166-1 Alpha 3-Codes', 'x Alpha2 codes', 'x Alpha3 codes', 'Preferred Term', 'ISO Alt Term', 'DGACM Alt Term', 'HPC Tools Alt Term', 'RW Short Name', 'RW API Alt Term', 'English Short', 'French Short', 'Spanish Short', 'Russian Short', 'Chinese Short', 'Arabic Short', 'English Formal', 'M49 English', 'M49 French', 'M49 Spanish', 'M49 Russian', 'M49 Chinese', 'M49 Arabic', 'Admin Level', 'Latitude', 'Longitude', 'Region Code', 'Region Name', 'Sub-region Code', 'Sub-region Name', 'Intermediate Region Code', 'Intermediate Region Name', 'Regex', 'World Bank Income Level', 'Currency', 'Reference Period Start', 'Concatenation']

In [9]:
# Coordonnées approximatives de la France (Paris)
france_lat, france_lon = 48.8566, 2.3522

def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # km
    phi1, phi2 = np.radians(lat1), np.radians(lat2)
    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)
    a = np.sin(delta_phi/2)**2 + np.cos(phi1)*np.cos(phi2)*np.sin(delta_lambda/2)**2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    return R * c

# Enlever les lignes sans coordonnées
df_pays['Latitude'] = pd.to_numeric(df_pays['Latitude'], errors='coerce').astype('float')
df_pays['Longitude'] = pd.to_numeric(df_pays['Longitude'], errors='coerce').astype('float')
coords = df_pays.dropna(subset=['Latitude', 'Longitude'])

# Calcul distance
coords['Distance_km'] = coords.apply(lambda x: haversine(france_lat, france_lon, x['Latitude'], x['Longitude']), axis=1)

# Extraire nom pays et distance
result = coords[['Preferred Term', 'Distance_km']].rename(columns={'Preferred Term': 'Pays'})

# Sauvegarder en CSV
result.to_csv('distance_vers_france.csv', index=False)

In [10]:
df_disf = pd.read_csv("distance_vers_france.csv")

In [11]:
df_disf.head()

             Pays   Distance_km
0     Afghanistan   5401.204279
1   Åland Islands   1682.970715
2         Albania   1630.684713
3         Algeria   2300.955396
4  American Samoa  16120.895717

In [12]:
df_disf["Année"] = 2017

In [13]:
df_disf.head()

             Pays   Distance_km  Année
0     Afghanistan   5401.204279   2017
1   Åland Islands   1682.970715   2017
2         Albania   1630.684713   2017
3         Algeria   2300.955396   2017
4  American Samoa  16120.895717   2017

In [16]:
df_colonne = ["Pays", "Distance_km"]
df_disf.loc[df_disf[df_colonne].isna().any(axis=1)]

Empty DataFrame
Columns: [Pays, Distance_km, Année]
Index: []